# Generated by Django 4.0.3 on 2022-03-30 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=250, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Courriel'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Portable'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendeur(se)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.FloatField(verbose_name='Montant €'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payement_due',
            field=models.DateField(verbose_name="Date d'échéance du paiement"),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sales_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendeur(se)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Contrat signé'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(verbose_name='Nombre de participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateField(auto_now_add=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(verbose_name="Date de l'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Créé', 'Créé'), ('Affecté', 'Affecté'), ('Terminé', 'Terminé')], max_length=20, verbose_name="Statut de l'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Portable'),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='team',
            field=models.CharField(choices=[('Support', 'Support'), ('Ventes', 'Ventes'), ('Gestion', 'Gestion')], max_length=20, verbose_name='Pôle'),
        ),
    ]
