# Generated by Django 4.0.3 on 2022-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_client_date_updated_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Créé', 'Created'), ('Affecté', 'Assigned'), ('Terminé', 'Finished')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('Support', 'Support'), ('Ventes', 'Sales'), ('Gestion', 'Management')], max_length=20),
        ),
    ]
