# Generated by Django 4.0.3 on 2022-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
